#!/usr/bin/env python3
"""Insert the island generated by port/tools/gen_island.py into
mock_routine.F90 at its markers -> mock_gen.F90 (T-CALLCHECK)."""
import os
import re
import subprocess
import sys

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "mock_routine.F90")
out = subprocess.run([sys.executable, os.path.join(here, "..", "..", "tools", "gen_island.py"), src, "calc_alt"],
                     capture_output=True, text=True, check=True).stdout
parts = re.split(r"^! \(\d\) .*$", out, flags=re.M)
use, decl, entry, exit_ = [p.strip("\n") for p in parts[1:5]]
use = "\n".join(l for l in use.split("\n") if "module_gpu_callcheck" in l)   # module_gpu_route is already used
text = open(src).read()
text = text.replace("!ISLAND-USE", use).replace("!ISLAND-ENTRY", entry).replace("!ISLAND-EXIT", exit_)
open(os.path.join(here, "mock_gen.F90"), "w").write(text)
print("mock_gen.F90 written")
