#!/usr/bin/env python3
"""Checks of the code generated by WRF's Registry tools for the GPU port
(plan.md P1.2, P1.3; port/agent/PHASE1.md tasks P1.2 and P1.3).

Run on a WRF build tree after './compile' (the Registry has written inc/).

  C1  every ALLOCATE(grid%X(...)) in inc/allocs.inc (in-use arrays, the
      (1,1,1) dummies and the boundary arrays) is followed, before the next
      ALLOCATE and after the initial-value assignment, by
          !$omp target enter data map(to:grid%X)
      inside '#ifdef WRF_GPU' ... '#endif' (plan.md P1.2)
  C2  the enter-data line of an in-use or dummy array sits under
      'IF (.NOT. grid%is_intermediate)' (intermediate grids stay on the host)
  C3  every DEALLOCATE(grid%X...) in inc/deallocs.inc is preceded, in the same
      IF block, by  !$omp target exit data map(delete:grid%X)  under WRF_GPU
  C4  inc/gpu_upd_dev_all.inc and inc/gpu_upd_host_all.inc contain a
      'target update to'/'from' of every allocated field
  C5  inc/gpu_upd_dev_bdy.inc updates every boundary array (_bxs, _bxe, _bys,
      _bye, _btxs, _btxe, _btys, _btye)
  C6  inc/gpu_upd_host_force_slab.inc covers every field packed by
      inc/nest_interpdown_pack.inc (the parent side of nest forcing)
  C7  every update line is guarded by IF (in_use_for_config(grid%id,'<name>'))

Usage: check_generated.py <WRF build dir> [--only C1,C3,...]
Exit status 0 if all selected checks pass.
"""

import argparse
import os
import re
import sys

ALLOC = re.compile(r"^\s*ALLOCATE\(\s*grid%(\w+)\s*\(", re.I)
DEALLOC = re.compile(r"^\s*DEALLOCATE\(\s*grid%(\w+)\s*[,)]", re.I)
ENTER = re.compile(r"^\s*!\$omp\s+target\s+enter\s+data\s+map\(\s*to\s*:\s*grid%(\w+)\s*\)", re.I)
EXIT = re.compile(r"^\s*!\$omp\s+target\s+exit\s+data\s+map\(\s*(delete|release)\s*:\s*grid%(\w+)\s*\)", re.I)
UPD = re.compile(r"^\s*!\$omp\s+target\s+update\s+(to|from)\s*\(\s*grid%(\w+)", re.I)
INUSE = re.compile(r"in_use_for_config\s*\(\s*grid%id\s*,\s*'(\w+)'", re.I)
BDY = re.compile(r"_b(t)?(xs|xe|ys|ye)$")


def read(path):
    return open(path, errors="replace").read().split("\n") if os.path.exists(path) else None


def check_allocs(lines):
    errs = []
    names = []
    starts = [i for i, l in enumerate(lines) if ALLOC.match(l)]
    for idx, i in enumerate(starts):
        name = ALLOC.match(lines[i]).group(1).lower()
        names.append(name)
        end = starts[idx + 1] if idx + 1 < len(starts) else len(lines)
        seg = lines[i:end]
        enter = [k for k, l in enumerate(seg) if ENTER.match(l) and ENTER.match(l).group(1).lower() == name]
        if not enter:
            errs.append(("C1", i + 1, f"no 'target enter data map(to:grid%{name})' after ALLOCATE"))
            continue
        k = enter[0]
        init = [kk for kk, l in enumerate(seg) if re.search(rf"grid%{name}\s*=\s*initial_data_value", l, re.I)]
        if init and init[0] > k:
            errs.append(("C1", i + k + 1, f"enter data of {name} before its initial value is set"))
        before = seg[:k]
        ifdef = [kk for kk, l in enumerate(before) if re.match(r"^\s*#\s*ifdef\s+WRF_GPU\b", l)]
        if not ifdef or any(re.match(r"^\s*#\s*endif", l) for l in before[ifdef[-1] + 1:]):
            errs.append(("C1", i + k + 1, f"enter data of {name} not inside #ifdef WRF_GPU"))
        # C2: intermediate guard, either the generated IF or the boundary-array condition
        ctx = "\n".join(lines[max(0, i - 3):i + k + 1])
        if not re.search(r"is_intermediate", ctx, re.I):
            errs.append(("C2", i + k + 1, f"enter data of {name} not guarded by .NOT. grid%is_intermediate"))
    return names, errs


def check_deallocs(lines):
    errs = []
    for i, l in enumerate(lines):
        m = DEALLOC.match(l)
        if not m:
            continue
        name = m.group(1).lower()
        seg = lines[max(0, i - 8):i]
        if not any(EXIT.match(x) and EXIT.match(x).group(2).lower() == name for x in seg):
            errs.append(("C3", i + 1, f"no 'target exit data map(delete:grid%{name})' before DEALLOCATE"))
    return errs


def upd_names(lines, code):
    names, errs = set(), []
    for i, l in enumerate(lines):
        m = UPD.match(l)
        if not m:
            continue
        name = m.group(2).lower()
        names.add(name)
        ctx = "\n".join(lines[max(0, i - 3):i])
        if not INUSE.search(ctx):
            errs.append(("C7", i + 1, f"{code}: update of {name} not guarded by in_use_for_config"))
    return names, errs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build")
    ap.add_argument("--only")
    args = ap.parse_args()
    inc = os.path.join(args.build, "inc")
    only = set(args.only.split(",")) if args.only else None
    results = {}

    def want(c):
        return only is None or c in only

    allocs = read(os.path.join(inc, "allocs.inc"))
    deallocs = read(os.path.join(inc, "deallocs.inc"))
    if allocs is None or deallocs is None:
        print(f"no inc/allocs.inc or inc/deallocs.inc in {args.build}: build first")
        return 2
    names, errs = check_allocs(allocs)
    all_names = set(names)
    field_names = {n for n in all_names}
    bdy_names = {n for n in all_names if BDY.search(n)}
    for c in ("C1", "C2"):
        if want(c):
            results[c] = [e for e in errs if e[0] == c]
    if want("C3"):
        results["C3"] = check_deallocs(deallocs)
    upd_files = {"C4a": "gpu_upd_dev_all.inc", "C4b": "gpu_upd_host_all.inc", "C5": "gpu_upd_dev_bdy.inc",
                 "C6": "gpu_upd_host_force_slab.inc"}
    guard_errs = []
    for code, fname in upd_files.items():
        base = code[:2]
        if not want(base) and not want("C7"):
            continue
        lines = read(os.path.join(inc, fname))
        if lines is None:
            if want(base):
                results.setdefault(base, []).append((base, 0, f"inc/{fname} does not exist"))
            continue
        got, g = upd_names(lines, fname)
        guard_errs += g
        if code.startswith("C4"):
            need = field_names
        elif code == "C5":
            need = bdy_names
        else:
            pack = read(os.path.join(inc, "nest_interpdown_pack.inc")) or []
            need = {m.lower() for l in pack for m in re.findall(r"grid%(\w+)", l)}
        missing = sorted(need - got)
        if want(base):
            results.setdefault(base, [])
            for mname in missing[:50]:
                results[base].append((base, 0, f"inc/{fname}: no update of grid%{mname}"))
            if len(missing) > 50:
                results[base].append((base, 0, f"inc/{fname}: ... {len(missing) - 50} more missing"))
    if want("C7"):
        results["C7"] = guard_errs

    bad = 0
    for c in sorted(results):
        errs = results[c]
        print(f"{c}: {'PASS' if not errs else 'FAIL (' + str(len(errs)) + ')'}")
        for e in errs[:15]:
            print(f"   {('line ' + str(e[1]) + ': ') if e[1] else ''}{e[2]}")
        if len(errs) > 15:
            print(f"   ... {len(errs) - 15} more")
        bad += bool(errs)
    print(f"check_generated: {len(all_names)} ALLOCATE statements ({len(bdy_names)} boundary arrays): "
          f"{'PASS' if not bad else 'FAIL'}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
