#!/usr/bin/env python3
"""Checks of the code generated by WRF's Registry tools for the GPU port
(plan.md P1.2, P1.3; port/agent/PHASE1.md tasks P1.2 and P1.3).

Run on a WRF build tree after './compile' (the Registry has written inc/).

  The generated code moves fields by address through WRF/frame/module_gpu_map.F:
      CALL gpu_map_r(grid%X, &
        SIZE(grid%X,KIND=8), GPU_MAP_ENTER)      (gpu_map_r/_d/_i/_l by type)

  C1  every ALLOCATE(grid%X(...)) in inc/allocs.inc (in-use arrays, the
      (1,1,1) dummies and the boundary arrays) is followed, before the next
      ALLOCATE and after the initial-value assignment, by a GPU_MAP_ENTER call
      of grid%X inside '#ifdef WRF_GPU' ... '#endif' (plan.md P1.2)
  C2  that call is guarded, on the line before it, by
      'IF (.NOT. grid%is_intermediate) &' (intermediate grids stay on the host)
  C3  every DEALLOCATE(grid%X...) in inc/deallocs.inc is preceded, in the same
      IF block, by a GPU_MAP_EXIT call of grid%X
  C4  inc/gpu_upd_dev_all.inc (GPU_UPD_TO) and inc/gpu_upd_host_all.inc
      (GPU_UPD_FROM) move every allocated field, in the right direction
  C5  inc/gpu_upd_dev_bdy.inc moves every boundary array (_bxs, _bxe, _bys,
      _bye, _btxs, _btxe, _btys, _btye) host -> device
  C6  inc/gpu_upd_host_force_slab.inc covers every field packed by
      inc/nest_interpdown_pack.inc (the parent side of nest forcing; Phase 5)
  C7  every update call is guarded by IF (in_use_for_config(grid%id,'<name>'))
      naming the same field, within the 3 lines above it, except the boundary arrays, which allocs.inc allocates unconditionally
      (IF(.TRUE.)...); <name> of a derived-type component is 'type%comp'

Usage: check_generated.py <WRF build dir> [--only C1,C3,...]
Exit status 0 if all selected checks pass.
"""

import argparse
import os
import re
import sys

ALLOC = re.compile(r"^\s*ALLOCATE\(\s*grid%(\w+)\s*\(", re.I)
DEALLOC = re.compile(r"^\s*DEALLOCATE\(\s*grid%(\w+)\s*[,)]", re.I)
CALL = re.compile(r"^\s*CALL\s+gpu_map_[rdil]\s*\(\s*grid%(\w+)((?:%\w+)*)\s*,", re.I)
OP = re.compile(r"\bGPU_(MAP_ENTER|MAP_EXIT|UPD_TO|UPD_FROM)\b", re.I)
INUSE = re.compile(r"in_use_for_config\s*\(\s*grid%id\s*,\s*'([\w%]+)'", re.I)
BDY = re.compile(r"_b(t)?(xs|xe|ys|ye)$")


def read(path):
    return open(path, errors="replace").read().split("\n") if os.path.exists(path) else None


def map_calls(lines):
    """{line index: (name, component path, op)} of the gpu_map_* calls; the op
    may be on the continuation line"""
    out = {}
    for i, l in enumerate(lines):
        m = CALL.match(l)
        if not m:
            continue
        o = OP.search(l) or (OP.search(lines[i + 1]) if i + 1 < len(lines) else None)
        out[i] = (m.group(1).lower(), (m.group(1) + m.group(2)).lower(), o.group(1).upper() if o else "?")
    return out


def check_allocs(lines):
    errs = []
    names = []
    calls = map_calls(lines)
    starts = [i for i, l in enumerate(lines) if ALLOC.match(l)]
    for idx, i in enumerate(starts):
        name = ALLOC.match(lines[i]).group(1).lower()
        names.append(name)
        end = starts[idx + 1] if idx + 1 < len(starts) else len(lines)
        seg = lines[i:end]
        enter = [k for k in range(len(seg)) if i + k in calls and calls[i + k][0] == name
                 and calls[i + k][2] == "MAP_ENTER"]
        if not enter:
            errs.append(("C1", i + 1, f"no GPU_MAP_ENTER call of grid%{name} after ALLOCATE"))
            continue
        k = enter[0]
        init = [kk for kk, l in enumerate(seg) if re.search(rf"grid%{name}\s*=\s*initial_data_value", l, re.I)]
        if init and init[0] > k:
            errs.append(("C1", i + k + 1, f"device copy of {name} made before its initial value is set"))
        before = seg[:k]
        ifdef = [kk for kk, l in enumerate(before) if re.match(r"^\s*#\s*ifdef\s+WRF_GPU\b", l)]
        if not ifdef or any(re.match(r"^\s*#\s*endif", l) for l in before[ifdef[-1] + 1:]):
            errs.append(("C1", i + k + 1, f"GPU_MAP_ENTER of {name} not inside #ifdef WRF_GPU"))
        # C2: the guard on the line before the call
        if not re.search(r"\.NOT\.\s*grid%is_intermediate", lines[i + k - 1], re.I):
            errs.append(("C2", i + k + 1, f"GPU_MAP_ENTER of {name} not guarded by IF (.NOT. grid%is_intermediate)"))
    return names, errs


def check_deallocs(lines):
    errs = []
    calls = map_calls(lines)
    for i, l in enumerate(lines):
        m = DEALLOC.match(l)
        if not m:
            continue
        name = m.group(1).lower()
        if not any(c[0] == name and c[2] == "MAP_EXIT" for j, c in calls.items() if i - 8 <= j < i):
            errs.append(("C3", i + 1, f"no GPU_MAP_EXIT call of grid%{name} before DEALLOCATE"))
    return errs


def upd_names(lines, code, want_op):
    names, errs = set(), []
    for i, (name, path, op) in sorted(map_calls(lines).items()):
        names.add(name)
        if op != want_op:
            errs.append((code[:2], i + 1, f"{code}: grid%{path} moved with GPU_{op}, expected GPU_{want_op}"))
        if BDY.search(name):
            continue  # boundary arrays are always allocated at full size
        guards = [g.lower() for x in lines[max(0, i - 3):i] for g in INUSE.findall(x)]
        if path not in guards:
            errs.append(("C7", i + 1, f"{code}: update of {path} not guarded by in_use_for_config(grid%id,'{path}')"))
    return names, errs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build")
    ap.add_argument("--only")
    args = ap.parse_args()
    inc = os.path.join(args.build, "inc")
    only = set(args.only.split(",")) if args.only else None
    results = {}

    def want(c):
        return only is None or c in only

    allocs = read(os.path.join(inc, "allocs.inc"))
    deallocs = read(os.path.join(inc, "deallocs.inc"))
    if allocs is None or deallocs is None:
        print(f"no inc/allocs.inc or inc/deallocs.inc in {args.build}: build first")
        return 2
    names, errs = check_allocs(allocs)
    all_names = set(names)
    field_names = {n for n in all_names}
    bdy_names = {n for n in all_names if BDY.search(n)}
    for c in ("C1", "C2"):
        if want(c):
            results[c] = [e for e in errs if e[0] == c]
    if want("C3"):
        results["C3"] = check_deallocs(deallocs)
    upd_files = {"C4a": ("gpu_upd_dev_all.inc", "UPD_TO"), "C4b": ("gpu_upd_host_all.inc", "UPD_FROM"),
                 "C5": ("gpu_upd_dev_bdy.inc", "UPD_TO"), "C6": ("gpu_upd_host_force_slab.inc", "UPD_FROM")}
    guard_errs = []
    for code, (fname, want_op) in upd_files.items():
        base = code[:2]
        if not want(base) and not want("C7"):
            continue
        lines = read(os.path.join(inc, fname))
        if lines is None:
            if want(base):
                results.setdefault(base, []).append((base, 0, f"inc/{fname} does not exist"))
            continue
        got, g = upd_names(lines, fname, want_op)
        guard_errs += [e for e in g if e[0] == "C7"]
        if want(base):
            results.setdefault(base, []).extend(e for e in g if e[0] != "C7")
        if code.startswith("C4"):
            need = field_names
        elif code == "C5":
            need = bdy_names
        else:
            pack = read(os.path.join(inc, "nest_interpdown_pack.inc")) or []
            need = {m.lower() for l in pack for m in re.findall(r"grid%(\w+)", l)}
        missing = sorted(need - got)
        if want(base):
            results.setdefault(base, [])
            for mname in missing[:50]:
                results[base].append((base, 0, f"inc/{fname}: no update of grid%{mname}"))
            if len(missing) > 50:
                results[base].append((base, 0, f"inc/{fname}: ... {len(missing) - 50} more missing"))
    if want("C7"):
        results["C7"] = guard_errs

    bad = 0
    for c in sorted(results):
        errs = results[c]
        print(f"{c}: {'PASS' if not errs else 'FAIL (' + str(len(errs)) + ')'}")
        for e in errs[:15]:
            print(f"   {('line ' + str(e[1]) + ': ') if e[1] else ''}{e[2]}")
        if len(errs) > 15:
            print(f"   ... {len(errs) - 15} more")
        bad += bool(errs)
    print(f"check_generated: {len(all_names)} ALLOCATE statements ({len(bdy_names)} boundary arrays): "
          f"{'PASS' if not bad else 'FAIL'}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
