#!/usr/bin/env python3
"""Generate port/agent/ROUTES.md: for every route of WRF/frame/module_gpu_route.F,
the routines whose kernels it switches (definition file:lines in the CPU-view
base commit), every call site of those routines in the base commit, and its
kernel rows of port/agent/kernels.csv.

Usage: gen_routes_md.py [--check]
"""
import csv
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PORT = os.path.dirname(HERE)
REPO = os.path.dirname(PORT)
OUT = os.path.join(PORT, "agent", "ROUTES.md")
DIRS = ["WRF/dyn_em", "WRF/share", "WRF/phys", "WRF/frame", "WRF/main"]
PHASE_OF_SEC = {"7": 2, "8": 3, "9": 4, "10": 5, "5": 0}


def base_rev():
    for line in open(os.path.join(PORT, "agent", "cpu_view_base")):
        s = line.split("#")[0].strip()
        if s:
            return s


def routes():
    src = open(os.path.join(REPO, "WRF", "frame", "module_gpu_route.F")).read()
    body = src[src.index("route_name(nroutes)"):src.index("INTEGER, PARAMETER, PUBLIC :: &")]
    out, sec = [], ""
    for line in body.split("\n"):
        m = re.match(r"\s*!\s*([0-9.]+(?:-[0-9.]+)?)\s+(.*)", line)
        if m:
            sec = f"{m.group(1)} {m.group(2).strip()}"
            continue
        for nm in re.findall(r"'([a-z0-9_]+)\s*'", line):
            out.append((nm, sec))
    return out


def main():
    base = base_rev()
    rows = list(csv.DictReader(open(os.path.join(PORT, "agent", "kernels.csv"))))
    grep = subprocess.run(["git", "-C", REPO, "grep", "-n", "-i", "-E", r"^\s*(if\s*\(.*\)\s*)?call\s+\w+", base, "--"] + DIRS,
                          capture_output=True, text=True, errors="replace").stdout
    calls = {}
    for l in grep.split("\n"):
        m = re.match(r"[^:]+:([^:]+):(\d+):.*?\bcall\s+(\w+)", l, re.I)
        if m:
            calls.setdefault(m.group(3).lower(), []).append(f"{m.group(1).replace('WRF/', '')}:{m.group(2)}")
    md = ["# Routes: routines, definitions and call sites\n",
          f"Generated by `port/tools/gen_routes_md.py`. Line numbers are in the CPU-view base commit `{base[:12]}`.",
          "A route (`R_<NAME>` in `WRF/frame/module_gpu_route.F`) switches the kernels of its routines between device and",
          "host (`WRF_GPU_OFF=<name>`); the island of each routine moves its arguments (CODING_STANDARD.md §3). Call sites",
          "tell you where a routine runs (solve_em, init, nest forcing) and how often. Kernel rows: `KERNEL_REFS.md`.\n",
          "| Route | Plan section | Routines (definition, base commit) | Call sites (base commit) | Kernel rows |",
          "|---|---|---|---|---|"]
    for nm, sec in routes():
        rs = [r for r in rows if r["route"] == nm]
        defs = []
        for r in rs:
            for d in r["routines"].split("; "):
                if d and d not in defs:
                    defs.append(d)
        if not defs:
            sys.path.insert(0, HERE)
            from gen_kernels_csv import find_routine
            f, lr = find_routine(nm, [], base)
            if lr:
                defs.append(f"{nm} {f}:{lr[0]}-{lr[1] or '?'}")
        names = [d.split()[0] for d in defs] or [nm]
        cs = []
        for n in names:
            for c in calls.get(n.lower(), []):
                cs.append(f"{n}: {c}" if len(names) > 1 else c)
        keys = ", ".join(r["key"] for r in rs)
        md.append(f"| `{nm}` | {sec} | {'<br>'.join(defs) or '(see plan.md)'} | "
                  f"{'<br>'.join(cs[:14]) + (f'<br>... {len(cs) - 14} more' if len(cs) > 14 else '') or '-'} | {keys or '-'} |")
    text = "\n".join(md) + "\n"
    if "--check" in sys.argv:
        ok = os.path.exists(OUT) and open(OUT).read() == text
        print("ROUTES.md up to date" if ok else "ROUTES.md out of date")
        return 0 if ok else 1
    open(OUT, "w").write(text)
    print(f"{len(routes())} routes -> {os.path.relpath(OUT, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
